spring:
  application:
    name: user-service-provider
server:
  port: 7070

eureka:
  client:
    service-url:
      ### 默认 Eureka 服务器地址
      defaultZone: http://localhost:8761/eureka

### 关闭安全检查
management:
  security:
    enabled: false
